import RXSMarketplace_2 from './contracts/RXSMarketplace.json';
import ArcaneTraderV1_2 from './contracts/ArcaneTraderV1.json';
import RuneShards_2 from './contracts/RuneShards.json';
import ArcaneBarracksV1_2 from './contracts/ArcaneBarracksV1.json';
import ArcaneBarracksV2_2 from './contracts/ArcaneBarracksV2.json';
import ArcaneBlacksmithV4_2 from './contracts/ArcaneBlacksmithV4.json';
import ArcaneBlacksmithV5_2 from './contracts/ArcaneBlacksmithV5.json';
import ArcaneWorldstoneMinterV1_2 from './contracts/ArcaneWorldstoneMinterV1.json';
import ArcaneItemStorageV1_2 from './contracts/ArcaneItemStorageV1.json';
import RuneSenderV1_2 from './contracts/RuneSenderV1.json';
import RuneBlacksmith_2 from './contracts/RuneBlacksmith.abi.json';
import PancakeRouterV2_2 from './contracts/PancakeRouterV2.abi.json';
import RuneTimelock_2 from './contracts/RuneTimelock.abi.json';

export const RXSMarketplace = RXSMarketplace_2;
export const ArcaneTraderV1 = ArcaneTraderV1_2;
export const RuneShards = RuneShards_2;
export const ArcaneBarracksV1 = ArcaneBarracksV1_2;
export const ArcaneBarracksV2 = ArcaneBarracksV2_2;
export const ArcaneBlacksmithV4 = ArcaneBlacksmithV4_2;
export const ArcaneBlacksmithV5 = ArcaneBlacksmithV5_2;
export const ArcaneWorldstoneMinterV1 = ArcaneWorldstoneMinterV1_2;
export const ArcaneItemStorageV1 = ArcaneItemStorageV1_2;
export const RuneSenderV1 = RuneSenderV1_2;
export const RuneBlacksmith = RuneBlacksmith_2;
export const PancakeRouterV2 = PancakeRouterV2_2;
export const RuneTimelock = RuneTimelock_2;
